### ISSUE TITLE
Quick note

### ISSUE THREAD

**Issue by MostHated** [dkopec91/GridIt#1]
Hey there, I just wanted to say thanks for releasing this, it is absolutely perfect for what I was needing. Not being able to line things up in applications which don't include any sort of built-in grid or snapping has been driving my OCD batty. 

Thanks,
-MH

**Comment by dkopec91** [comment]
Hello @MostHated,

Thank you so much for your feedback. It's great to know that someone besides me found it useful! :smile:

Regards,
Daniel
